# Generated by Django 3.1.5 on 2021-01-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicabio', '0002_remove_paciente_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='user',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dt_nascimento',
            field=models.DateField(max_length=15),
        ),
    ]
