# Generated by Django 3.1.5 on 2021-01-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicabio', '0003_auto_20210112_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf_paciente',
            field=models.CharField(default='Sem informações', max_length=13, unique=True),
        ),
    ]
