# Generated by Django 3.1.5 on 2021-01-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicabio', '0004_auto_20210112_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf_paciente',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
