# Generated by Django 3.1.5 on 2021-01-13 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sicabio', '0006_auto_20210112_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impressao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='media/avatar.png', null=True, upload_to='impressoes')),
                ('mao', models.CharField(choices=[('ME', 'Mão Esquerda'), ('MD', 'Mão Direita')], max_length=2)),
                ('dedo', models.CharField(max_length=200)),
                ('cont', models.IntegerField(default=1, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='im_digital', to='sicabio.paciente')),
            ],
        ),
    ]
