# Generated by Django 3.1.5 on 2021-01-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicabio', '0007_impressao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressao',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='impressoes'),
        ),
    ]
