# Generated by Django 3.1.5 on 2021-01-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicabio', '0008_auto_20210112_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impressao',
            old_name='img',
            new_name='an_di',
        ),
        migrations.RemoveField(
            model_name='impressao',
            name='cont',
        ),
        migrations.RemoveField(
            model_name='impressao',
            name='dedo',
        ),
        migrations.RemoveField(
            model_name='impressao',
            name='mao',
        ),
        migrations.AddField(
            model_name='impressao',
            name='an_es',
            field=models.ImageField(blank=True, null=True, upload_to='impressoes'),
        ),
        migrations.AddField(
            model_name='impressao',
            name='in_di',
            field=models.ImageField(blank=True, null=True, upload_to='impressoes'),
        ),
        migrations.AddField(
            model_name='impressao',
            name='in_es',
            field=models.ImageField(blank=True, null=True, upload_to='impressoes'),
        ),
        migrations.AddField(
            model_name='impressao',
            name='me_di',
            field=models.ImageField(blank=True, null=True, upload_to='impressoes'),
        ),
        migrations.AddField(
            model_name='impressao',
            name='me_es',
            field=models.ImageField(blank=True, null=True, upload_to='impressoes'),
        ),
        migrations.AddField(
            model_name='impressao',
            name='min_di',
            field=models.ImageField(blank=True, null=True, upload_to='impressoes'),
        ),
        migrations.AddField(
            model_name='impressao',
            name='min_es',
            field=models.ImageField(blank=True, null=True, upload_to='impressoes'),
        ),
        migrations.AddField(
            model_name='impressao',
            name='pol_es',
            field=models.ImageField(blank=True, null=True, upload_to='impressoes'),
        ),
        migrations.AddField(
            model_name='impressao',
            name='polegar esquerdo',
            field=models.ImageField(blank=True, null=True, upload_to='impressoes'),
        ),
    ]
