# Generated by Django 3.1.5 on 2021-01-13 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sicabio', '0009_auto_20210113_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impressao',
            old_name='an_es',
            new_name='anelar_di',
        ),
        migrations.RenameField(
            model_name='impressao',
            old_name='an_di',
            new_name='anelar_es',
        ),
        migrations.RenameField(
            model_name='impressao',
            old_name='in_di',
            new_name='indicador_di',
        ),
        migrations.RenameField(
            model_name='impressao',
            old_name='me_di',
            new_name='medio_di',
        ),
        migrations.RenameField(
            model_name='impressao',
            old_name='me_es',
            new_name='medio_es',
        ),
        migrations.RenameField(
            model_name='impressao',
            old_name='min_di',
            new_name='minimo_di',
        ),
        migrations.RenameField(
            model_name='impressao',
            old_name='min_es',
            new_name='minimo_es',
        ),
        migrations.RenameField(
            model_name='impressao',
            old_name='pol_es',
            new_name='polegar_di',
        ),
        migrations.RenameField(
            model_name='impressao',
            old_name='polegar esquerdo',
            new_name='polegar_es',
        ),
    ]
