# Generated by Django 3.1.5 on 2021-01-13 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sicabio', '0010_auto_20210113_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impressao',
            old_name='polegar_es',
            new_name='polega_es',
        ),
    ]
