# Generated by Django 3.1.5 on 2021-01-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicabio', '0013_auto_20210113_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressao',
            name='in_es',
            field=models.ImageField(blank=True, default='images/fingerprint_add.png', null=True, upload_to='impressoes'),
        ),
    ]
