# Generated by Django 3.1.5 on 2021-01-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicabio', '0014_auto_20210113_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impressao',
            name='anelar_di',
        ),
        migrations.RemoveField(
            model_name='impressao',
            name='anelar_es',
        ),
        migrations.RemoveField(
            model_name='impressao',
            name='in_es',
        ),
        migrations.RemoveField(
            model_name='impressao',
            name='indicador_di',
        ),
        migrations.RemoveField(
            model_name='impressao',
            name='medio_di',
        ),
        migrations.RemoveField(
            model_name='impressao',
            name='medio_es',
        ),
        migrations.RemoveField(
            model_name='impressao',
            name='minimo_di',
        ),
        migrations.RemoveField(
            model_name='impressao',
            name='minimo_es',
        ),
        migrations.RemoveField(
            model_name='impressao',
            name='polegar_di',
        ),
        migrations.RemoveField(
            model_name='impressao',
            name='polegar_es',
        ),
        migrations.AddField(
            model_name='impressao',
            name='img',
            field=models.ImageField(blank=True, default='media/avatar.png', null=True, upload_to='impressoes'),
        ),
    ]
