# Generated by Django 3.1.5 on 2021-02-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicabio', '0015_auto_20210122_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressao',
            name='img',
            field=models.ImageField(default='media/avatar.png', upload_to='impressoes'),
        ),
    ]
