# Generated by Django 3.1.5 on 2021-02-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicabio', '0016_auto_20210209_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressao',
            name='img',
            field=models.ImageField(default='static/images/fingerprint_add.png', upload_to='impressoes'),
        ),
    ]
