# Generated by Django 3.1.5 on 2021-02-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicabio', '0017_auto_20210224_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressao',
            name='img',
            field=models.ImageField(default='', upload_to='impressoes'),
        ),
    ]
