# Generated by Django 3.1.5 on 2021-02-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicabio', '0018_auto_20210224_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressao',
            name='img',
            field=models.ImageField(default='/fingerprint_add.png', upload_to='impressoes'),
        ),
    ]
