# Generated by Django 3.1.5 on 2021-02-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicabio', '0019_auto_20210224_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressao',
            name='dedos',
            field=models.CharField(default='', max_length=200),
        ),
    ]
