# Generated by Django 3.1.5 on 2021-02-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicabio', '0020_impressao_dedos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressao',
            name='img',
            field=models.ImageField(default='', upload_to='impressoes'),
        ),
    ]
