# Generated by Django 3.1.5 on 2021-03-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicabio', '0021_auto_20210227_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressao',
            name='mao',
            field=models.CharField(default='', max_length=200),
        ),
    ]
