# Generated by Django 3.1.5 on 2021-03-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicabio', '0022_impressao_mao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf_paciente',
            field=models.CharField(default='', max_length=14, null=True, unique=True),
        ),
    ]
