# Generated by Django 3.1.5 on 2021-03-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicabio', '0023_auto_20210318_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf_paciente',
            field=models.CharField(blank=True, default='', max_length=14, null=True, unique=True),
        ),
    ]
