# Generated by Django 3.1.5 on 2021-03-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicabio', '0025_paciente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf_paciente',
            field=models.CharField(blank=True, default='', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dt_nascimento',
            field=models.DateField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_paciente',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
