# Generated by Django 3.1.5 on 2021-03-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicabio', '0026_auto_20210319_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf_paciente',
            field=models.CharField(blank=True, default='Sem Informação', max_length=14),
        ),
    ]
