# Generated by Django 3.1.5 on 2021-03-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicabio', '0027_auto_20210319_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dt_nascimento',
            field=models.DateField(max_length=15),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_paciente',
            field=models.CharField(max_length=100),
        ),
    ]
